steps:
  - name: ':docker:'
    plugins:
      docker-compose#v3.5.0:
        build: xviz
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders

  - wait

  - name: ':eslint:'
    command: 'yarn lint'
    plugins:
      docker-compose#v3.5.0:
        run: xviz
    agents:
      queue: workers

  - name: ':node:'
    command: 'yarn test-ci'
    plugins:
      docker-compose#v3.5.0:
        run: xviz
    agents:
      queue: workers

  - name: ':chrome:'
    command: 'yarn test browser-headless'
    plugins:
      docker-compose#v3.5.0:
        run: xviz
    agents:
      queue: workers
